#!/bin/bash -e
command -v realpath >/dev/null 2>&1 || { echo "realpath is required but it's not installed, aborting." >&2; exit 1; }
DATE=$(date +"%Y%m%d")
ARCH="$1"
API="$2"
VARIANT="full"
VENDOR_PATH=vendor/opengapps
ANDROID_BUILD_TOP=~/x7k/android/lollipop/
VENDOR_ABSOLUTE_PATH="${ANDROID_BUILD_TOP}/${VENDOR_PATH}"
SOURCES="${VENDOR_ABSOLUTE_PATH}/sources"
TOP="${VENDOR_ABSOLUTE_PATH}/tools"
SCRIPTS="$TOP/scripts"
OUT="$TOP/aosp/"

. "$SCRIPTS/inc.aromadata.sh"
. "$SCRIPTS/inc.buildhelper.sh"
. "$SCRIPTS/inc.buildtarget.sh"
. "$SCRIPTS/inc.compatibility.sh"
. "$SCRIPTS/inc.installdata.sh"
. "$SCRIPTS/inc.packagetarget.sh"
. "$SCRIPTS/inc.updatebinary.sh"
. "$SCRIPTS/inc.tools.sh"

get_gapps_list $VARIANT

buildlib() {
    sourceapk="$1"
    targetdir="$build/$2"
    apkarch="$3"

    #echo "TODO buildlib: $@"
}

relative_to_vendor() {
  echo "$1" | sed "s/.*vendor/vendor/g"
}

build_dpi_src_files() {
   sourceapk=$1
}

buildapk() {
    sourceapk="$1"
    targetdir="$2"

    module_name=$(basename $targetdir)
    module_dir=$(basename $(dirname $targetdir))

    if [[ "$sourceapk" != *"nodpi"* ]]; then
      echo "$sourceapk: is not NODPI...ignoring"
      return
    fi
    echo "buildapk $@"

    module_path="$OUT/$module_name/"
    mkdir -p "$module_path"

    cat << EOF > "$module_path/Android.mk"
# Autogenerated Makefile from OpenGapps. Do not modify.
LOCAL_PATH := .
include \$(CLEAR_VARS)

LOCAL_MODULE := ${module_name}
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := \$(PRODUCT_OUT)/system/${module_dir}
LOCAL_SRC_FILES := $(relative_to_vendor $sourceapk)
LOCAL_CERTIFICATE := PRESIGNED

include \$(BUILD_PREBUILT)
EOF

    echo "generated $module_name ( $(relative_to_vendor "$sourceapk") )"
    echo 
}
build=$OUT

for app in $gapps_list; do
    get_package_info "$app"
    if [ -n "$packagename" ]; then
        buildapp "$packagename" "$packagetype/$app" "$packagetarget"
    fi
    for file in $packagefiles; do
        echo "buildfile $packagetype/$app/common $file"
    done
done
